version: '3.8'
services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: 12345678
      POSTGRES_DB: turamyzba
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data

  app:
    build: .
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/turamyzba
      SPRING_DATASOURCE_USERNAME: test
      SPRING_DATASOURCE_PASSWORD: 12345678
    ports:
      - "8080:8080"
    depends_on:
      - db

volumes:
  db-data:
