spring:
  application:
    name: Shanyraq

  datasource:
    driverClassName: org.postgresql.Driver
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5433/Turamyzba}
    username: ${DATABASE_USERNAME:postgres}
    password: ${DATABASE_PASSWORD:zhandos04}
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        show_sql: true
    hibernate:
      ddl-auto: update
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 1000MB

  flyway:
    enabled: true
    url: jdbc:postgresql://localhost:5432/turamyzba
    user: test
    password: 12345678
    locations: classpath:db/migration

  mail:
    host: smtp.gmail.com
    port: 587
    username: turamyzba@gmail.com
    password: wasn ftdo frbe isjb
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

2gis:
  api:
    key: ${2GIS_API_KEY:d419b4a6-8b9a-4a5c-9a69-ca5946b1bb76}
    url: https://catalog.api.2gis.com/3.0/items

aws:
  accessKey: ${AWS_ACCESS_KEY_ID:AKIAU6GDZF7KB27CUXDX}
  secretKey: ${AWS_SECRET_ACCESS_KEY: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}
  s3:
    region: ${AWS_REGION:eu-north-1}
    bucket: ${S3_BUCKET_NAME:findroommate}

jwt:
  secret: f20be2a4a63bb8c9f2b5ecbed7f0971a96d66e30f3f7c76b56a6e0361ea8e76a

server:
  servlet:
    context-path: '/api/'
  error:
    include-message: always
  port: ${PORT:8080}
  address: 0.0.0.0